---
- name: Configure sudo with no password prompt
  copy:
    content: '{{ lookup("env", "USER") }} ALL=(ALL{{ ":" }}ALL) NOPASSWD{{ ":" }} ALL'
    dest: '/etc/sudoers.d/{{ lookup("env", "USER") }}'
    mode: '0440'
    validate: '/usr/sbin/visudo -csf %s'
  become: 'yes'

- name: Reset connection
  meta: reset_connection
