---
- name: Include debian essential packages
  set_fact:
    essential_packages: "{{ essential_packages + debian_essential_packages }}"
  when: ansible_os_family == 'Debian'

- name: Ensure critical components installed
  include_role:
    name: roles/install_package
  vars:
    packages:
    - git
    - curl
    install_latest: yes

- name: Ensure critical python components installed
  pip:
    name:
    - pexpect
    state: latest
  become: no
