---
- name: Upgrade homebrew packages
  community.general.homebrew:
    update_homebrew: >-
      {%- if not homebrew_updated -%} yes
      {%- else -%} no
      {%- endif -%}
    upgrade_all: yes
  when: upgrade == True
  become: no

- name: Install homebrew packages
  community.general.homebrew:
    name: "{{ packages }}"
    state: >-
      {%- if install_latest -%} latest
      {%- else -%} present
      {%- endif -%}
    update_homebrew: >-
      {%- if not homebrew_updated and not upgrade -%} yes
      {%- else -%} no
      {%- endif -%}
  become: no

- name: Remember homebrew state
  set_fact:
    homebrew_updated: yes
  when: not homebrew_updated
  become: no
