- name: Set ansible_user if undefined
  set_fact: ansible_user="{{ ansible_ssh_user | default(ansible_env.USER, true) }}"
  when: ansible_user is undefined

- name: Get ansible_user home directory on Linux
  block:
  - shell: |
      getent passwd "{{ ansible_user }}" | cut -d: -f6
    changed_when: False
    register: ansible_home_result
  - name: Set the fact for the other scripts to use
    set_fact: user_home='{{ ansible_home_result.stdout }}'
  when: ansible_os_family != 'Darwin'
  become: no

- name: Get ansible_user home directory on MacOS
  block:
  - name: get home directory on macOS
    shell: echo $HOME
    changed_when: False
    register: ansible_home_result
  - name: Set the fact for the other scripts to use
    set_fact: user_home='{{ ansible_home_result.stdout }}'
  when: ansible_os_family == 'Darwin'
  become: no

- debug: var=user_home
